---

- hosts: amazon_linux_2
  connection: ssh
  gather_facts: true
  become: yes

  vars:
    cis_level_1_exclusions:
      - '1.1.6'
      - '1.1.7'
      - '1.1.8'
      - '1.1.9'
      - '1.1.10'
      - '1.1.11'
      - '1.1.12'
      - '1.1.13'
      - '1.1.14'
      - '1.1.19'
      - '1.4.3' #surprisingly absent in my CIS version

  roles:
    - { role: ansible-cis-amazon-linux-2,
        in_vm: true,
        cis_enable_rsyslog: true
      }