# Standards: 0.11
---

# 1.1.1.3 - Ensure mounting of hfsplus filesystems is disabled

- name: 1.1.1.3 - Ensure mounting of hfsplus filesystems is disabled
  modprobe:
    name: hfsplus
    state: absent
  tags:
    - level-1
    - section-1
    - "1.1.1.3"
    - scored