---
# Standards: 0.11

# 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled

- name: 1.1.1.1 - Unload cramfs module
  modprobe:
    name: cramfs
    state: absent
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

