# Standards: 0.11
---

# 1.1.1.4 - Ensure mounting of squashfs filesystems is disabled

- name: 1.1.1.4 - Ensure mounting of squashfs filesystems is disabled
  modprobe:
    name: squashfs
    state: absent
  tags:
    - level-1
    - section-1
    - "1.1.1.4"
    - scored