# Standards: 0.11
---

# 1.1.1.2 - Ensure mounting of freevxfs filesystems is disabled

- name: 1.1.1.2 - Unload freevxfs module
  modprobe:
    name: freevxfs
    state: absent
  tags:
    - level-1
    - section-1
    - "1.1.1.2"
    - scored
