# Standards: 0.11
---

# 1.1.1.5 - Ensure mounting of udf filesystems is disabled

- name: 1.1.1.5 - Ensure mounting of udf filesystems is disabled
  modprobe:
    name: udf
    state: absent
  tags:
    - level-1
    - section-1
    - "1.1.1.5"
    - scored