# Standards: 0.11
---

# 1.1.1.2 - Ensure mounting of hfs filesystems is disabled (scored)

- name: 1.1.1.2 - Ensure mounting of hfs filesystems is disabled (scored)
  modprobe:
    name: hfs
    state: absent
  tags:
    - level-1
    - section-1
    - "1.1.1.2"
    - scored
