# Standards: 0.11
---

# 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)

- name: 1.6.1.1 - Install the SE Linux requirements - libselinux-python
  yum:
    name: libselinux-python
    state: present
  tags:
    - level-1
    - "1.6.1.1"
    - scored

- name: 1.6.1.1 Ensure SELinux is enabled in bootloader configuration if it was previously disabled (Scored)
  replace:
    dest: "{{ cis_grub_configuration_filename }}"
    regexp: '{{ item }}=0'
  with_items:
    - selinux
    - enforcing
  notify: Reconfigure GRUB

  tags:
    - level-1
    - "1.6.1.1"
    - scored
